#!/bin/bash

# .bashrc
echo ". ~/dotfiles/alias" >> ~/.bashrc

# zsh
rm -i ~/.bash_login
ln -s ~/dotfiles/_bash_login ~/.bash_login
rm -i ~/.zshrc
ln -s ~/dotfiles/_zshrc ~/.zshrc

# tmux
rm -i ~/.tmux.conf
ln -s ~/dotfiles/_tmux.conf ~/.tmux.conf

# git
rm -i ~/.gitconfig
ln -s ~/dotfiles/_gitconfig ~/.gitconfig

# vim
rm -i ~/.vimrc
rm -ri ~/.vim
ln -s ~/dotfiles/_vimrc ~/.vimrc
mkdir ~/.vim
ln -s ~/dotfiles/_vim/colors ~/.vim/colors
ln -s ~/dotfiles/_vim/ftdetect ~/.vim/ftdetect
ln -s ~/dotfiles/_vim/ambiwidth.vimrc ~/.vim/ambiwidth.vimrc

# xvim
rm -i ~/.xvimrc
ln -s ~/dotfiles/_xvimrc ~/.xvimrc

# powerline
if [ ! -d ~/.config ]; then
    mkdir ~/.config
fi
rm -ri ~/.config/powerline
ln -s ~/dotfiles/_config/powerline ~/.config/powerline


# Submodule
git submodule init
git submodule update
