#!/bin/bash

# .bashrc
echo ". ~/dotfiles/_bashrc_plus" >> ~/.bashrc

# tmux
rm -i ~/.tmux.conf
ln -s ~/dotfiles/_tmux.conf ~/.tmux.conf

# vim
rm -i ~/.vimrc
rm -ri ~/.vim
ln -s ~/dotfiles/_vimrc ~/.vimrc
mkdir ~/.vim
ln -s ~/dotfiles/_vim/colors ~/.vim/colors

# Submodule
git submodule init
git submodule update
